#!/usr/bin/env python
"""
Title: pveretention
Author: Michael Chinn
License: apache-2.0
Url: https://github.com/mechinn/pveretention
"""
import argparse, re, datetime, glob, os, sys

dateFormat = "%Y_%m_%d-%H_%M_%S"


def rmBackup(execute,location,vm,backup):
    for file in glob.glob(os.sep.join([location,"-".join(["vzdump",vm,backup.strftime(dateFormat)])+".*"])):
        if execute:
            print('Removing: '+file)
            os.remove(file)
        else:
            print("Dry Run Removing: "+file)

def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    description="""
        Keep Proxmox Virtual Environment backups based on given retention.
        Either keep a number of backups for each VM or keep backups made within the last number of days.
        The user can also specify a limited set of VMs which this program should work on.
    """)
    parser.add_argument('--debug', action='store_true', help=argparse.SUPPRESS)
    parser.add_argument('-l','--location', default='/var/lib/vz/dump', help='Manually set the location of the backups')
    parser.add_argument('--vm', action='append', default=['All'], help='Specify the VM(s) which should be included with this')
    modes = parser.add_mutually_exclusive_group(required=True)
    modes.add_argument('-d','--days', type=int, help='The number of days backups should be kept')
    modes.add_argument('-c','--count', type=int, help='The number of backups that should be kept')

    args = parser.parse_args()

    args.vm.remove("All")
    
    if args.debug:
        print("debug mode")

    files = []
    for (dirpath, dirnames, filenames) in os.walk(args.location):
        files.extend(filenames)
        break

    vms = {}
    logSearch = re.compile("(.+)\.log$")
    for filename in files:
        description = logSearch.match(filename)
        if description:
            descriptionParts = description.group(1).split("-")
            key = "-".join(descriptionParts[1:3])
            if len(args.vm) > 0:
                if descriptionParts[2] not in args.vm:
                    continue
            if key not in vms:
                vms[key] = []
            vms[key].append(datetime.datetime.strptime("-".join(descriptionParts[3:5]),dateFormat))

    for vm, backups in vms.items():
        if args.days is None:
            if args.count < 0:
                print("count cannot be negative: {0}".format(args.count))
                sys.exit(1)
            backups.reverse()
            for backup in backups[args.count:]:
                rmBackup(not args.debug,args.location,vm,backup)
        else:
            cutoff = datetime.datetime.today() - datetime.timedelta(days=args.days)
            for backup in backups:
                if backup < cutoff:
                    rmBackup(not args.debug,args.location,vm,backup)


if __name__ == '__main__':
    main()
